#!/bin/sh

ip addr add 10.1.1.1/24 dev eth0
ip link set eth0 up

ip link add vxlan10 type vxlan id 10 group 239.1.1.1 dstport 4789 dev eth0
ip link set vxlan10 up

brctl addbr br0
brctl addif br0 vxlan10
brctl addif br0 eth1
ip link set br0 up
ip link set eth1 up
