#!/bin/sh

ip addr add 10.1.1.6/30 dev eth0
ip link set eth0 up
ip link set eth1 up

ip addr add 1.1.1.3/32 dev lo
ip link set lo up

ip link add vxlan10 type vxlan id 10 dstport 4789 local 1.1.1.3 nolearning
ip link set vxlan10 up

brctl addbr br0
brctl addif br0 vxlan10
brctl addif br0 eth1
ip link set br0 up

vtysh << 'EOF'
configure terminal
!
hostname _sshevche-3
!
router ospf
 network 10.1.1.4/30 area 0
 network 1.1.1.3/32 area 0
!
router bgp 65000
 bgp router-id 1.1.1.3
 no bgp default ipv4-unicast
 !
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 update-source lo
 !
 address-family l2vpn evpn
  neighbor 1.1.1.1 activate
  advertise-all-vni
 exit-address-family
!
end
write memory
EOF
